name: Bug Report
description: Report a bug or technical issue
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ianandersonlol

body:
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: |
        Please describe the bug in detail.
        The chat history has been automatically copied to your clipboard.
      placeholder: Tell us what you experienced and what went wrong
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen instead
    validations:
      required: true