name: Bug Report (from Chat)
description: Report a bug or technical issue encountered within the chat interface
title: "[Bug - Chat]: "
labels: ["bug", "from-chat"]
assignees:
  - ianandersonlol

body:
  - type: textarea
    id: conversation_history
    attributes:
      label: Conversation History
      description: Please paste the relevant conversation history here
      placeholder: "Paste conversation history here"
    validations:
      required: false

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Please describe the bug in detail
      placeholder: Tell us what you experienced and what went wrong
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen instead
    validations:
      required: false
