name: Model Accuracy Issue
description: Report when the model provides inaccurate food information
title: "[Model Accuracy]: "
labels: ["model-accuracy"]
assignees:
  - ianandersonlol

body:
  - type: textarea
    id: food_query
    attributes:
      label: Food or Query
      description: What specific food or query did you ask about?
      placeholder: "e.g., 'nutritional content of quinoa' or 'compare spinach vs kale'"
    validations:
      required: true

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: |
        Describe what the model said and what was incorrect about it.
        The chat history has been automatically copied to your clipboard.
      placeholder: Tell us what the model responded with and why it was inaccurate
    validations:
      required: true