name: Model Accuracy Issue (from Chat)
description: Report when the model provides inaccurate food information from within the chat interface
title: "[Model Accuracy - Chat]: "
labels: ["model-accuracy", "from-chat"]
assignees:
  - ianandersonlol

body:
  - type: textarea
    id: conversation_history
    attributes:
      label: Conversation History
      description: Please paste the relevant conversation history here
      placeholder: "Paste conversation history here"
    validations:
      required: false

  

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe what the model said and what was incorrect about it
      placeholder: Tell us what the model responded with and why it was inaccurate
    validations:
      required: true

  - type: textarea
    id: correct_information
    attributes:
      label: Correct Information (Optional)
      description: If you know the correct information, please provide it
      placeholder: "e.g., 'Quinoa has 14g protein per 100g, not 10g'"
    validations:
      required: false
